name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build and Run
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Show status
        run: |
          ls -la
          docker-compose ps -a

      - name: Run checkings
        run: |
          docker-compose -f docker-compose.yml exec -T olhaduto-desktop yarn prestart
          docker-compose -f docker-compose.yml exec -T olhaduto-desktop yarn test
          docker-compose -f docker-compose.yml exec -T olhaduto-desktop yarn lint
          docker-compose -f docker-compose.yml exec -T olhaduto-desktop yarn lint-styles
